import AppKit

/// Types from nspasteboard.org that clipboard managers honour: the item is
/// short-lived, must not be shown or stored, and was not copied by a person.
enum PasteboardMarkers {
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")
    static let all: [NSPasteboard.PasteboardType] = [transient, concealed, autoGenerated]
}

/// Every item and every type on a pasteboard, byte for byte.
struct PasteboardSnapshot: Equatable {
    struct Entry: Equatable {
        let type: NSPasteboard.PasteboardType
        let data: Data
    }
    let items: [[Entry]]

    static func take(of pasteboard: NSPasteboard) -> PasteboardSnapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in item.data(forType: type).map { Entry(type: type, data: $0) } }
        }
        return PasteboardSnapshot(items: items.filter { !$0.isEmpty })
    }

    /// Put the snapshot back. An empty snapshot leaves an empty pasteboard.
    @discardableResult
    func write(to pasteboard: NSPasteboard) -> Bool {
        pasteboard.clearContents()
        guard !items.isEmpty else { return true }
        let restored = items.map { entries -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for entry in entries { item.setData(entry.data, forType: entry.type) }
            return item
        }
        return pasteboard.writeObjects(restored)
    }
}

/// The transcript, promised rather than written: the pasteboard asks for the
/// string only when an app actually reads it, and that request is the receipt
/// that the paste was taken. Called on whatever thread AppKit chooses, so all
/// state sits behind a lock.
final class TranscriptPromise: NSObject, NSPasteboardItemDataProvider, @unchecked Sendable {
    private let text: String
    private let lock = NSLock()
    private var armedAt: UInt64?
    private var readsBeforeArm = 0
    private var readsAfterArm: [UInt64] = []

    init(text: String) {
        self.text = text
    }

    /// Mark the moment Cmd+V goes out. Reads before it are not receipts.
    func arm(at time: UInt64 = DispatchTime.now().uptimeNanoseconds) {
        lock.lock()
        armedAt = time
        lock.unlock()
    }

    struct Reads: Equatable {
        let beforeArm: Int
        let afterArm: Int
        /// Nanoseconds from arming to the first receipt.
        let firstReceiptDelay: UInt64?
    }

    var reads: Reads {
        lock.lock()
        defer { lock.unlock() }
        let delay = readsAfterArm.first.flatMap { first in armedAt.map { first >= $0 ? first - $0 : 0 } }
        return Reads(beforeArm: readsBeforeArm, afterArm: readsAfterArm.count, firstReceiptDelay: delay)
    }

    func pasteboard(
        _ pasteboard: NSPasteboard?,
        item: NSPasteboardItem,
        provideDataForType type: NSPasteboard.PasteboardType
    ) {
        let now = DispatchTime.now().uptimeNanoseconds
        lock.lock()
        if armedAt == nil {
            readsBeforeArm += 1
        } else {
            readsAfterArm.append(now)
        }
        lock.unlock()
        item.setString(text, forType: type == .string ? .string : type)
    }
}

/// One paste: snapshot the user's pasteboard, promise the transcript, and put
/// the user's content back afterwards — only while the pasteboard is still
/// ours, so a copy the user makes in between is never overwritten.
@MainActor
final class PasteboardTransaction {
    let pasteboard: NSPasteboard
    let snapshot: PasteboardSnapshot
    let promise: TranscriptPromise
    let ownChangeCount: Int
    private(set) var isClosed = false

    enum Close: String, Equatable {
        /// The user's items are back.
        case restored
        /// Someone wrote the pasteboard after us; their content stays.
        case keptForeignWrite = "kept_foreign_write"
        /// Restoring failed; the transcript may still be there.
        case restoreFailed = "restore_failed"
        /// The transcript was left on purpose, as plain text, for a manual paste.
        case leftTranscript = "left_transcript"
    }

    private init(pasteboard: NSPasteboard, snapshot: PasteboardSnapshot, promise: TranscriptPromise, ownChangeCount: Int) {
        self.pasteboard = pasteboard
        self.snapshot = snapshot
        self.promise = promise
        self.ownChangeCount = ownChangeCount
    }

    /// Snapshot, then write the promise with the manager markers. Nil when the
    /// pasteboard refused the write (the user's content is put back first).
    static func begin(text: String, on pasteboard: NSPasteboard, sourceBundleID: String?) -> PasteboardTransaction? {
        let snapshot = PasteboardSnapshot.take(of: pasteboard)
        let promise = TranscriptPromise(text: text)
        let item = NSPasteboardItem()
        guard item.setDataProvider(promise, forTypes: [.string]) else { return nil }
        for marker in PasteboardMarkers.all {
            item.setData(Data(), forType: marker)
        }
        if let sourceBundleID {
            item.setString(sourceBundleID, forType: PasteboardMarkers.source)
        }
        pasteboard.clearContents()
        guard pasteboard.writeObjects([item]) else {
            snapshot.write(to: pasteboard)
            return nil
        }
        return PasteboardTransaction(
            pasteboard: pasteboard,
            snapshot: snapshot,
            promise: promise,
            ownChangeCount: pasteboard.changeCount
        )
    }

    var stillOwned: Bool { pasteboard.changeCount == ownChangeCount }

    /// Give the user's pasteboard back. Idempotent.
    @discardableResult
    func restore() -> Close {
        guard !isClosed else { return .restored }
        isClosed = true
        guard stillOwned else { return .keptForeignWrite }
        return snapshot.write(to: pasteboard) ? .restored : .restoreFailed
    }

    /// Replace the promise with the plain transcript for a manual paste.
    /// A plain string outlives this process; a promise would not.
    @discardableResult
    func leaveTranscript(_ text: String) -> Close {
        guard !isClosed else { return .leftTranscript }
        isClosed = true
        guard stillOwned else { return .keptForeignWrite }
        pasteboard.clearContents()
        guard pasteboard.setString(text, forType: .string) else { return .restoreFailed }
        return .leftTranscript
    }
}
