// Generated by scripts/generate-whisperkit-catalog.py — do not edit by hand.
//
// Every hash below belongs to one immutable commit of
// argmaxinc/whisperkit-coreml. Re-run the generator when the pin moves.

import Foundation

enum WhisperKitAssetCatalog {
    static let repository = "argmaxinc/whisperkit-coreml"

    /// Immutable Hugging Face commit. Never replace this with `main`:
    /// every expected hash below belongs to this exact snapshot.
    static let revision = "97a5bf9bbc74c7d9c12c755d04dea59e672e3808"

    /// openai_whisper-large-v3-v20240930_turbo_632MB — 22 files, 645,668,913 bytes.
    static let largeV3V20240930Turbo632MB: [GigaAMAssetDescriptor] = [
        .init(
            relativePath: "AudioEncoder.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "0dd9f529c744ed3c6be67f699588f7aadc4f366b5b7301dc31bd3f199944fbcc"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/coremldata.bin",
            expectedByteCount: 348,
            expectedSHA256: "ffa9eb76e8e9d9be75a4d527e5249e61d67fd43081c5aa110fd24efa6c8c5ea3"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/metadata.json",
            expectedByteCount: 1_974,
            expectedSHA256: "2cd0538f90a012de3f07d38669026d527490eff1dcfd2479a81c48206a90f0a2"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/model.mil",
            expectedByteCount: 7_589_739,
            expectedSHA256: "ef5a252831e61bb91d6547fe1add3d0658895b518d47d70004322b40a2192668"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/weights/weight.bin",
            expectedByteCount: 421_968_768,
            expectedSHA256: "e4740fa28ed65907af754af893dfce98473fafb84dd8d718ad346985fe7678c1"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "c5be419f8622083ac7046306400643539f0e7577c843448c36defc090d41e7ce"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/coremldata.bin",
            expectedByteCount: 329,
            expectedSHA256: "98efa1e351b759e078c4044668926d32bee886caf7596ae897e08e21da45565a"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/metadata.json",
            expectedByteCount: 1_850,
            expectedSHA256: "2bc552e09a6f124d9e6c178dd1a6979e010206acb26308b2224887c9dcbeb35f"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/model.mil",
            expectedByteCount: 10_143,
            expectedSHA256: "c270b95b5f81d7f7d0b8a3e8f991d4e5812a37cad29349868a35b91f3a6a4463"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/weights/weight.bin",
            expectedByteCount: 373_376,
            expectedSHA256: "009d9fb8f6b589accfa08cebf1c712ef07c3405229ce3cfb3a57ee033c9d8a49"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "4b5119bdc621c3c494f63846dc3ed43852e88826fc3b6345d42272d4b7e67724"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/coremldata.bin",
            expectedByteCount: 633,
            expectedSHA256: "605dad4099a82cf2c7afe93e6d8e322f1c16d4160ab27bd017ec2517b81c1bdd"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/metadata.json",
            expectedByteCount: 4_924,
            expectedSHA256: "e3ce6d83884552ffcc2c34799e8e1211dcda59f1aaea5a79bf988c6cd16abbf0"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/model.mil",
            expectedByteCount: 217_177,
            expectedSHA256: "ebaf8566f367b6465276c3ed57bb99063888fa955b67828585bf19db24c85f56"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/weights/weight.bin",
            expectedByteCount: 203_199_860,
            expectedSHA256: "d69700903d518ada33170ab77faaaf464496fb9ff65752c6d5a6109aa2fb02db"
        ),
        .init(
            relativePath: "TextDecoderContextPrefill.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "97639d36c7b137ea51c3c39b175911788f4d4a601ab03cd67a4b14164c3145e1"
        ),
        .init(
            relativePath: "TextDecoderContextPrefill.mlmodelc/coremldata.bin",
            expectedByteCount: 380,
            expectedSHA256: "2c159f5c862ec187092ea58e755d8c0b298952e22f3d75da023d7693c1c7389e"
        ),
        .init(
            relativePath: "TextDecoderContextPrefill.mlmodelc/metadata.json",
            expectedByteCount: 2_240,
            expectedSHA256: "eb88dc350fa6748a8bc3fa5fb10958152c138752ebbbac1824d2f99b4c9fc068"
        ),
        .init(
            relativePath: "TextDecoderContextPrefill.mlmodelc/model.mil",
            expectedByteCount: 4_092,
            expectedSHA256: "990ff5052fd817e28ba7c34d9d06d324c69c7c0630b6eaac9cfdf08329dbcb34"
        ),
        .init(
            relativePath: "TextDecoderContextPrefill.mlmodelc/weights/weight.bin",
            expectedByteCount: 12_288_192,
            expectedSHA256: "1310070082639173e9d81508c5f220692d489e85655aa6883cc1c7506da7fcfd"
        ),
        .init(
            relativePath: "config.json",
            expectedByteCount: 1_149,
            expectedSHA256: "f01d83dd891791d6f12421c05d3ed8ebbe70866f10d6c9a7a7e80b558ce5a0f1"
        ),
        .init(
            relativePath: "generation_config.json",
            expectedByteCount: 2_767,
            expectedSHA256: "7fbb053a023be11fbeccd8421811610308143daa93d9617c52aab4a0fa1491c6"
        ),
    ]

    /// openai_whisper-large-v3_turbo — 24 files, 3,195,115,988 bytes.
    static let largeV3Turbo: [GigaAMAssetDescriptor] = [
        .init(
            relativePath: "AudioEncoder.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "b68eb75cef8a4b3585423dca03d42d2f6ff34029421ad11752ea5be85c9bbf4c"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/coremldata.bin",
            expectedByteCount: 348,
            expectedSHA256: "273d6cd004f95763e9d03e5d36622f11038819a81b9eafed64b1d95444e04f62"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/metadata.json",
            expectedByteCount: 1_877,
            expectedSHA256: "c3240968ef73f0930faac76d1b83e0645a69ea0ffdc29480622a673ba7d5edd9"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/model.mil",
            expectedByteCount: 7_006_617,
            expectedSHA256: "184871550eeaec5466016a55612fdcaec92dfefedafa0f92a7b47de0062316f2"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/model.mlmodel",
            expectedByteCount: 408_667,
            expectedSHA256: "bf0987c0d8c3fe180877b12ba5b4ac1d890e011f2103926e53186089feced575"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/weights/weight.bin",
            expectedByteCount: 1_273_974_400,
            expectedSHA256: "6f46870171555792f9e98d5266d2c7d885a18962093b3a9544fffa54dbe8df16"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "091a361134891f94e613562771beea0d93a9aefbc6984ba86c60f856e07a508f"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/coremldata.bin",
            expectedByteCount: 329,
            expectedSHA256: "f3c5778c86d6fbc6a9817a56dbcac05a946a4d95c77f6db8355572f3be9e9a68"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/metadata.json",
            expectedByteCount: 1_850,
            expectedSHA256: "4ae78f40c33992b394b5d163b13db7e5af3fb35332849409486e8c3cb99faec4"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/model.mil",
            expectedByteCount: 10_187,
            expectedSHA256: "17977ed2332430c6cc4c1da2516f2cd4deb662d65ae38d72725ab157f32d4949"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/weights/weight.bin",
            expectedByteCount: 373_376,
            expectedSHA256: "2eb5f443dc3a0a0ee0b5931e2c1a2365e6ab557b58f6ca46af26ea09ec1f7d57"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "09cdcc47a8297a8441b48a3b2859cc75f57c808bc11654f92678188c923533f8"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/coremldata.bin",
            expectedByteCount: 637,
            expectedSHA256: "7b49d28fd16bdc6c790a6cca7ff99f83838cec338d84fe44469fa93f16953489"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/metadata.json",
            expectedByteCount: 4_770,
            expectedSHA256: "e6a954d6887eccdd513bc3dcd9be1f22e91e7c1545f804c03641b52f8dee67e7"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/model.mil",
            expectedByteCount: 1_010_477,
            expectedSHA256: "418707ff1eab973fe11b0b0cbcb5b4bb7f5c3cee0de0ef11633b412f5e213416"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/model.mlmodel",
            expectedByteCount: 805_204,
            expectedSHA256: "a99dd7d7d5412c5be4e3dcd8725e7fa0c9f9c2c8d41cb037bf42084f478717b0"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/weights/weight.bin",
            expectedByteCount: 1_813_201_716,
            expectedSHA256: "745c0c3896c41cd6ad01b6c3ed852e0bb1cb2fd1ef579017c5cc9a8aff1d3c66"
        ),
        .init(
            relativePath: "TextDecoderContextPrefill.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "352d00fa1b9b29c06b538013f6b2884029d673a2a246abcd783d5581c4f04c83"
        ),
        .init(
            relativePath: "TextDecoderContextPrefill.mlmodelc/coremldata.bin",
            expectedByteCount: 382,
            expectedSHA256: "a91550bdd77216fd43a9b00251b6b5aebbcb2a2eee5ca92b2b3cdd0b8aa75971"
        ),
        .init(
            relativePath: "TextDecoderContextPrefill.mlmodelc/metadata.json",
            expectedByteCount: 2_236,
            expectedSHA256: "d3e0c9240ee80218a6d5ca3e06aab95ed13b41c2fcca126a18ac269d71208010"
        ),
        .init(
            relativePath: "TextDecoderContextPrefill.mlmodelc/model.mil",
            expectedByteCount: 3_778,
            expectedSHA256: "1698212287a0f05df7cb3f5d32f8a9050f0ca6b7b5cbd41f55bb6a9fe54b1d4c"
        ),
        .init(
            relativePath: "TextDecoderContextPrefill.mlmodelc/weights/weight.bin",
            expectedByteCount: 98_304_192,
            expectedSHA256: "40b8dc9229eb9627feff2abc3eae6370df0a1536334b11bc26ec307ebc463bfe"
        ),
        .init(
            relativePath: "config.json",
            expectedByteCount: 1_163,
            expectedSHA256: "798b69c08cf93b2b03d94bea6eb3eb25fd4712259712d8a62ed2483fdf818a9e"
        ),
        .init(
            relativePath: "generation_config.json",
            expectedByteCount: 2_810,
            expectedSHA256: "d24f9cca0f448609a71ae044b736023706382f45e9700e0dffb2559d10cf1fea"
        ),
    ]

    /// openai_whisper-medium — 20 files, 1,529,654,233 bytes.
    static let medium: [GigaAMAssetDescriptor] = [
        .init(
            relativePath: "AudioEncoder.mlcomputeplan.json",
            expectedByteCount: 91_482,
            expectedSHA256: "8f163b1d7f16d3f9647e61d015807bec163638495ea5c24f00a4b67771a6e506"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "1ac17e8f029504f6ecb645f539e039e650428b135cbed2d4234a4e65fde271d5"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/coremldata.bin",
            expectedByteCount: 347,
            expectedSHA256: "d875fd7e0a389117711940fc2052b29dc4ed0fd07813265a13cb041ae068f805"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/metadata.json",
            expectedByteCount: 1_799,
            expectedSHA256: "0ae579eda748a315d8fa9efb81c3c3de2747441d83581f1c571384148b5ac810"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/model.mil",
            expectedByteCount: 396_719,
            expectedSHA256: "cc283d26dcb5b6e873ab17fa761fb14cb9f240e94fe8a21ae94ce6e33282fc3b"
        ),
        .init(
            relativePath: "AudioEncoder.mlmodelc/weights/weight.bin",
            expectedByteCount: 614_460_544,
            expectedSHA256: "577c78ed7e0ae71f9ed6fdb063dc74a0f4c0c44d04118111650458973f7ddae6"
        ),
        .init(
            relativePath: "MelSpectrogram.mlcomputeplan.json",
            expectedByteCount: 4_004,
            expectedSHA256: "c6fd6ed4c86bc6d9bdcc4e5e9adead3415530019a9f1c9aa88a91900a1b07b14"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "847173d00b238eb63f0d3dab36dc52b7a3fd1d4b31e95d4093975fada8fde2cd"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/coremldata.bin",
            expectedByteCount: 328,
            expectedSHA256: "ebbb4bf9699f7d65018645e168ecedf47541eee154800f9e9766f1ac90746416"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/metadata.json",
            expectedByteCount: 1_878,
            expectedSHA256: "ae5fb57757692926faa57f89f2345c8d1efe20b73ac9df535bde195522e3b248"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/model.mil",
            expectedByteCount: 10_132,
            expectedSHA256: "646b86a0fa5a89c95b0de55f696751047f18b040fbc183a19c343da8d9d8838b"
        ),
        .init(
            relativePath: "MelSpectrogram.mlmodelc/weights/weight.bin",
            expectedByteCount: 354_080,
            expectedSHA256: "801024dbc7a89c677be1f8b285de3409e35f7d1786c9c8d9d0d6842ac57a1c83"
        ),
        .init(
            relativePath: "TextDecoder.mlcomputeplan.json",
            expectedByteCount: 186_396,
            expectedSHA256: "2987c54dce6bb9b2bbc44c3a128b16f24b4596689f66fc13cffcc7d673deef9e"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/analytics/coremldata.bin",
            expectedByteCount: 243,
            expectedSHA256: "c314ca0a7738acc7ac9f4c04da834cf46972c697bd1a6c5413c18e9d278a3c81"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/coremldata.bin",
            expectedByteCount: 637,
            expectedSHA256: "aed3dffd67cc0be59aa28a552d8963cb27ec29d60996ede9fc74162fa09af0a4"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/metadata.json",
            expectedByteCount: 4_800,
            expectedSHA256: "acc50d3b46186a8ad076b51fc0a1094dedc85bc9fdbb1c23f223f90845a81b9a"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/model.mil",
            expectedByteCount: 707_858,
            expectedSHA256: "1f4da05ff4415307adb526829834c66d3ddc2c3abe112bfbddbfc0404d50f55a"
        ),
        .init(
            relativePath: "TextDecoder.mlmodelc/weights/weight.bin",
            expectedByteCount: 913_428_274,
            expectedSHA256: "283878d285cb0e557eeb1c6a1524eb5fd33cae2c289a114bc9e72ca76c0bfc75"
        ),
        .init(
            relativePath: "config.json",
            expectedByteCount: 1_472,
            expectedSHA256: "25857725440d110777730fc27762b9c2415f068282dcc9535cf9d929740f9894"
        ),
        .init(
            relativePath: "generation_config.json",
            expectedByteCount: 2_754,
            expectedSHA256: "9e805015e900f8c96138cc3db93843bccc1912fa17a188abbdefcfbe1bf25734"
        ),
    ]

    /// Assets for a `.whisperKit` variant, or nil when the variant is not pinned here.
    static func assets(forVariant variant: String) -> [GigaAMAssetDescriptor]? {
        switch variant {
        case "large-v3-v20240930_turbo_632MB": return largeV3V20240930Turbo632MB
        case "large-v3_turbo": return largeV3Turbo
        case "medium": return medium
        default: return nil
        }
    }

    /// Absolute download URL for one asset of `variant`.
    static func resolveURL(for asset: GigaAMAssetDescriptor, variant: String) -> URL {
        var components = URLComponents()
        components.scheme = "https"
        components.host = "huggingface.co"
        components.path =
            "/\(repository)/resolve/\(revision)/openai_whisper-\(variant)/\(asset.relativePath)"
        components.queryItems = [URLQueryItem(name: "download", value: "1")]
        return components.url!
    }
}
